In [60]:
import pandas as pd
import glob

In [149]:
df = pd.DataFrame()
for filename in glob.iglob('./mol_csv/mol_*.csv'):
    df = df.append(pd.read_csv(filename, index_col=0))

"Склеиваем" все .csv файлы в один.

In [150]:
df

,f_id,f_chembl,h_id,h_chembl,f_smiles,h_smiles,assay_id,assay_chembl,assay_type,target_id,...,target_type,f_type,f_relation,f_value,f_units,h_type,h_relation,h_value,h_units,result
0,2211789,CHEMBL4071878,2226432,CHEMBL4086521,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,1677823,CHEMBL4027966,B,100650,...,SINGLE PROTEIN,Kd,=,500.0,nM,Kd,=,390.0000,nM,NaN
1,2211789,CHEMBL4071878,2226432,CHEMBL4086521,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,1677824,CHEMBL4027967,B,100157,...,SINGLE PROTEIN,Kd,=,8.7,nM,Kd,=,28.0000,nM,NaN
2,2211789,CHEMBL4071878,2226432,CHEMBL4086521,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,O=C(NCc1cn([C@@H]2[C@@H](O)[C@H](SS[C@@H]3O[C@...,1677825,CHEMBL4027968,B,22226,...,UNCHECKED,Ratio,=,57.0,NaN,Ratio,=,14.0000,NaN,NaN
3,2211802,CHEMBL4071891,2242241,CHEMBL4102330,Cc1c(-c2ccc(-n3cc(F)c(F)c3)cc2)[nH]c2cc(F)cc(F...,Cc1c(-c2ccc(-n3cccc3)cc2)[nH]c2cc(F)cc(F)c2c1=O,1699719,CHEMBL4050701,A,102342,...,TISSUE,T1/2,>=,1.0,hr,T1/2,=,0.5017,hr,NaN
4,2211802,CHEMBL4071891,2242241,CHEMBL4102330,Cc1c(-c2ccc(-n3cc(F)c(F)c3)cc2)[nH]c2cc(F)cc(F...,Cc1c(-c2ccc(-n3cccc3)cc2)[nH]c2cc(F)cc(F)c2c1=O,1699718,CHEMBL4050700,A,102280,...,TISSUE,T1/2,>=,1.0,hr,T1/2,=,0.3450,hr,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,789332,CHEMBL1365448,864038,CHEMBL1440154,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccc(F)cc3)ccc21,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccccc3)ccc21,737137,CHEMBL1737902,F,22226,...,UNCHECKED,Potency,NaN,17782.8,nM,Potency,NaN,20596.2000,nM,NaN
1210,789332,CHEMBL1365448,864038,CHEMBL1440154,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccc(F)cc3)ccc21,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccccc3)ccc21,737042,CHEMBL1738588,F,104005,...,SINGLE PROTEIN,Potency,NaN,8912.5,nM,Potency,NaN,35481.3000,nM,NaN
1211,789332,CHEMBL1365448,864038,CHEMBL1440154,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccc(F)cc3)ccc21,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccccc3)ccc21,752313,CHEMBL1794352,F,101018,...,SINGLE PROTEIN,Potency,NaN,23934.1,nM,Potency,NaN,16944.1000,nM,NaN
1212,789332,CHEMBL1365448,864038,CHEMBL1440154,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccc(F)cc3)ccc21,Cn1c(CN2CCCCC2)nc2cc(NC(=O)c3ccccc3)ccc21,1301620,CHEMBL3215181,F,22226,...,UNCHECKED,Potency,NaN,9466.2,nM,Potency,NaN,26679.5000,nM,NaN
1213,789384,CHEMBL1365500,337411,CHEMBL369996,O=C1CC(N2CCN(c3ccc(F)cc3)CC2)C(=O)N1c1ccc(F)cc1,O=C1CC(N2CCN(c3ccc(F)cc3)CC2)C(=O)N1c1ccccc1,752493,CHEMBL1794483,F,100972,...,SINGLE PROTEIN,Potency,NaN,100000.0,nM,Potency,NaN,56234.1000,nM,NaN

In [151]:
data = df.copy()
data = data[data.f_value.notnull()] 
data = data[data.h_value.notnull()]
data = data[data.f_units.notnull()]
data = data[data.h_units.notnull()]
data = data[data.f_relation.notnull()]
data = data[data.h_relation.notnull()]

data = data[data.f_value != 0]
data = data[data.h_value != 0]

data = data[data.f_relation == '=']
data = data[data.h_relation == '=']

data = data[data.target_type == 'SINGLE PROTEIN']

data = data[data.h_units == data.f_units]


data = data.reset_index(drop=True)

data.result = data.f_value / data.h_value

Берем только корректные данные: где указано значение, где значение не 0. Также оставляем только те строки, где значения констант со знаком =, это сделано для упрощения и наделения смыслом подсчета result, т.к. не совсем очевидно, что делать, если для молекулы с водородом константа > x, а для молекулы с фтором < y. Оставляем только строки, где совпадают единицы измерения (units).

In [152]:
data[['f_value', 'h_value', 'result']]

        f_value  h_value    result
0         500.0    390.0  1.282051
1           8.7     28.0  0.310714
2          93.0     93.0  1.000000
3         870.0   1600.0  0.543750
4        1050.0   3240.0  0.324074
...         ...      ...       ...
102995   2511.9   7079.5  0.354813
102996  39810.7  19952.6  1.995264
102997   3981.1   5011.9  0.794329
102998  25118.9  28183.8  0.891253
102999  15848.9   2238.7  7.079510

[103000 rows x 3 columns]

In [153]:
cols = list(data.columns)
cols = [col for col in cols if not col.endswith('_id')]
data = data[cols]

In [154]:
data.to_csv('clear_single_protein_decimal_comma.csv', decimal=",", sep=";")

Создаем итоговый .csv файл.